version: '3.8'

services:
  semob-front:
    container_name: semob-front-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080/api # Exemplo de injeção da URL de API do backend
    ports:
      - "80:80"
    restart: always
